<?php

/**
 * Created by PhpStorm.
 * User: reals
 * Date: 4/24/2017
 * Time: 4:26 PM
 */
class TmstUserCustom extends TmstUser
{
    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    public static function namaPeminjamKendaraan($id) {
        $model = TrxPeminjamanKendaraanCustom::model()->findByPk($id);
        $model_user = TmstUserCustom::model()->findByPk($model->id_peminjam);
        //echo "<pre>";var_dump($model);die;
        if($model_user) {
            return $model_user->username;
        }
    }
    public static function namaPeminjamKendaraanByUserId($userid) {
        $model_user = TmstUserCustom::model()->findByPk($userid);
        //echo "<pre>";var_dump($model);die;
        if($model_user) {
            return $model_user->username;
        }
    }
}