<?php

/**
 * This is the model class for table "tmst_inventaris".
 *
 * The followings are the available columns in table 'tmst_inventaris':
 * @property integer $id
 * @property string $nama
 *
 * The followings are the available model relations:
 * @property TranPerbaikanInventaris[] $tranPerbaikanInventarises
 */
class TmstInventarisCustom extends TmstInventaris
{

	public function rules()
    {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        $defaultRule = parent::rules();
        /*$newRule = array(
            array('kendaraan_id, peminjam, waktu_mulai, waktu_selesai', 'required')  ,
//            array('MIN_REQUEST','numerical','integerOnly'=>true,'min'=>1,'max'=>9999999),
            //array('MAX_REQUEST','notLessThanMin')
        );*/

        return $defaultRule; //array_merge($defaultRule, $newRule);
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    public function namaPelaporPerbaikan($id)
    {
        # code...
    }

    public static function getNamaInventaris($id)
    {
        $invent = TmstInventaris::model()->findByPk($id);
        if($invent) return $invent->nama;
        else return '';
    }
}
