<?php
/**
 * Created by PhpStorm.
 * User: reals
 * Date: 7/11/2017
 * Time: 11:25 PM
 */
class TranPeminjamanRuanganCustom extends TranPeminjamanRuangan
{
    public function rules()
    {
        $defaultRule = parent::rules();
        $newRule = array(
        );

        return array_merge($defaultRule, $newRule);
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    public static function TotalPeminjamanRuanganByUser($userid, $status) {
        $sql="
        select count(*) total from notifikasi
        where table_name = 'tran_peminjaman_ruangan' and status_id = ".$status." and user_id = ".$userid;
        $data = Yii::app()->db->createCommand($sql);
        $rawData = $data->queryAll();
        $count = $rawData[0]['total'];
        return $count;
    }

    public static function TotalPeminjamanRuanganForAdmin($status) {
        $today = (new DateTime())->setTimeZone(new DateTimeZone('Asia/Jakarta'));
        $sql="
        select count(*) total from tran_peminjaman_ruangan
        where status_id = ".$status . " and waktu_awal_peminjaman > ". "'" . $today->format('Y-m-d H:i') . "'";
        $data = Yii::app()->db->createCommand($sql);
        $rawData = $data->queryAll();
        $count = $rawData[0]['total'];
        return $count;
    }
}